# 应用配置
app:
  # 应用监听端口
  port: 7001
  name: joke-go


# Mysql数据库运行环境
mysql:
  env: development
  dialect: mysql
  db: db
  user: user
  password: password
  host: 127.0.0.1
  port: 3306
  showSql: true

# PostgreSQL 数据库运行环境
pg:
  env: development
  dialect: postgres
  db: db
  user: user
  password: password
  host: host
  port: 5432
  showSql: true

# 日志文件存放路径
logger:
  dir: /public/logs
  level: DEBUG