# 应用配置
app:
  # 应用监听端口
  port: 5001

# Mysql数据库运行环境
mysql:
  env: production
  dialect: mysql
  db: qushi
  user: root
  password: zenghr0820
  host: 127.0.0.1
  port: 3306
  showSql: false

# PostgreSQL 数据库运行环境
pg:
  env: production
  dialect: postgres
  db: qiushi
  user: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  showSql: true

# 日志文件存放路径
logger:
  dir: /server/joke/logs
  level: INFO