development:
  dialect: mysql
  database: qushi
  user: root
  password: zenghr0820
  host: 127.0.0.1
  port: 3306
  pool: 5

test:
  dialect: mysql
  database: qushi
  user: root
  password: zenghr0820
  host: 127.0.0.1
  port: 3306
  # url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/joke-go_test?sslmode=disable"}}

production:
  dialect: mysql
  database: qushi
  user: root
  password: zenghr0820
  host: 127.0.0.1
  port: 3306
  # url: {{ env "DATABASE_URL" }}
  # url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/joke-go_production?sslmode=disable"}}
